version: '3.4'

services:
  fprime-devcontainer:
    image: nasafprime/fprime-devcontainer
    build:
      context: .
      dockerfile: ./.devcontainer/Dockerfile
    volumes:
      - "../fprime-tools:/workspaces/fprime-tools"
      - ".:/workspaces/fprime"
      - "~/.ssh:/home/fprime/.ssh"
      - "~/.config/gh:/home/fprime/.config/gh"
    command: -c "while sleep 1000; do :; done"
